name: Craft Inc. Gates
version: 2.1.0
description: A plugin to create gates for fast traveling.
softdepend: [Vault]
author: tomco, s1m0ne
authors: [oloflarsson, locutus, DrAgonmoray, s1m0ne, tomco]
website: http://www.craftinc.de/craftinc-gates/

main: de.craftinc.gates.Plugin
database: false

commands:
  gate:
    description: All of the Craft Inc. Gates commands
    usage: See documentation or type '/gate help' while playing.

permissions:
  craftincgates.*:
    description: Gives access to all ancient gates commands and lets you use open gates.
    children:
      craftincgates.info: true
      craftincgates.use: true
      craftincgates.manage: true
  craftincgates.info:
    description: Gives access to info and list commands.
  craftincgates.use:
    default: true
    description: Allows you to use open gates.
  craftincgates.manage:
    description: Gives access to commands manipulating gates.
