name: AncientGates
version: 1.1.1
description: A plugin to create gates for fast traveling.
author: tomco
authors: [oloflarsson, locutus, DrAgonmoray, s1m0ne, tomco]
website: http://www.craftinc.de/blog/?p=255

main: org.mcteam.ancientgates.Plugin
database: false

commands:
  gate:
    description: All of the AncientGates commands
    usage: See documentation or type '/gate help' while playing.

permissions:
  ancientgates.*:
    description: Gives access to all ancient gates commands and lets you use open gates.
    children:
      ancientgates.info: true
      ancientgates.use: true
      ancientgates.manage: true
  ancientgates.info:
    description: Gives access to info and list commands.
  ancientgates.use:
    description: Allows you to use open gates.
  acientgates.manage:
    description: Gives access to commands manipulating gates.


